import type { AppProps } from "next/app";
import Head from "next/head";
import { ThirdwebProvider } from "@thirdweb-dev/react";
import { CHAIN } from "../const/chains";
import { Nav } from "../components/Navbar";
import { cn } from "@/lib/utils";
import "../styles/globals.css";

import { Inter as FontSans } from "next/font/google";
import localFont from "next/font/local";
import { SiteFooter } from "@/components/Footer";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

// Font files can be colocated inside of `pages`
const fontHeading = localFont({
  src: "../assets/fonts/CalSans-SemiBold.woff2",
  variable: "--font-heading",
});

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>EVM Kit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
          fontHeading.variable
        )}
      >
        <ThirdwebProvider
          // Set active chain for app
          activeChain={CHAIN}
          // Auth (SIWE) configuration
          authConfig={{
            domain: process.env.NEXT_PUBLIC_AUTH_DOMAIN || "evmkit.com", // Your website domain
            authUrl: "/api/auth", // API Route (default is - pages/api/auth/[...thirdweb].ts)
          }}
        >
          <Nav />
          <div className="h-24" />
          <Component {...pageProps} />
          <SiteFooter className="border-t" />
        </ThirdwebProvider>
      </main>
    </>
  );
}

export default MyApp;
